export const produce = [
  {
    name: "apple",
    availability: {
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      january: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "apricot",
    availability: {
      january: "Available",
      february: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "avocado",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
      may: "Unavailable",
      june: "Unavailable",
    },
  },
  {
    name: "banana",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "blackberry",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      december: "Available",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "blackcurrant",
    availability: {
      january: "Available",
      february: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "blueberry",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      november: "Available",
      december: "Available",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "boysenberry",
    availability: {
      january: "Available",
      november: "Available",
      december: "Available",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "cherry",
    availability: {
      january: "Available",
      december: "Available",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "feijoa",
    availability: {
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      january: "Unavailable",
      february: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "gooseberry",
    availability: {
      december: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "grapefruit",
    availability: {
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "black grapes",
    availability: {
      february: "Available",
      march: "Available",
      january: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "green grapes",
    availability: {
      february: "Available",
      march: "Available",
      january: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "honeydew melon",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "kiwiberry",
    availability: {
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "gold kiwifruit",
    availability: {
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "green kiwifruit",
    availability: {
      january: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
      february: "Unavailable",
      march: "Unavailable",
    },
  },
  {
    name: "lemon",
    availability: {
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "lime",
    availability: {
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      january: "Unavailable",
      february: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "mandarin",
    availability: {
      may: "Available",
      june: "Available",
      july: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "mango",
    availability: {
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      january: "Unavailable",
      february: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "nashi",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "nectarine",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "navel orange",
    availability: {
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
    },
  },
  {
    name: "orange",
    availability: {
      january: "Available",
      february: "Available",
      november: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "passionfruit",
    availability: {
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      january: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "peach",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      december: "Available",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "pear",
    availability: {
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      january: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "pineapple",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "plum",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "raspberry",
    availability: {
      january: "Available",
      december: "Available",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "redcurrant",
    availability: {
      january: "Available",
      december: "Available",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "strawberry",
    availability: {
      january: "Available",
      february: "Available",
      november: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "tamarillo",
    availability: {
      july: "Available",
      august: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "tangelo",
    availability: {
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
    },
  },
  {
    name: "watermelon",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      december: "Available",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "rock melon",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "globe artichoke",
    availability: {
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "jerusalem artichoke",
    availability: {
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "asparagus",
    availability: {
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
    },
  },
  {
    name: "beans",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      november: "Available",
      december: "Available",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "beetroot",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      november: "Available",
      december: "Available",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "broccoli",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "broccolini",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "brussel sprouts",
    availability: {
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "buttercup squash",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      december: "Available",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "butternut",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      december: "Available",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "cabbage",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "capsicum",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "carrot",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "cauliflower",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "celery",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "chilli",
    availability: {
      april: "Available",
      may: "Available",
      june: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "courgette",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
    },
  },
  {
    name: "cucumber",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "eggplant",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      november: "Available",
      december: "Available",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "fennel",
    availability: {
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      january: "Unavailable",
      february: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "fresh herbs",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "garlic",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "ginger",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "kale",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "kohlrabi",
    availability: {
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "kumara",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "leek",
    availability: {
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      january: "Unavailable",
      february: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "lettuce",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "mushroom",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "onion",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "parsnip",
    availability: {
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      january: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "pea",
    availability: {
      january: "Available",
      february: "Available",
      november: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "potato",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "pumpkin",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "puha",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "radish",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "salad greens",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "silverbeet",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "snow peas",
    availability: {
      january: "Available",
      february: "Available",
      november: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
    },
  },
  {
    name: "spinach",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "spring onion",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "bean sprouts",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "swede",
    availability: {
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      january: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "corn",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "taewa",
    availability: {
      january: "Available",
      february: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "taro",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "tomato",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "turnip",
    availability: {
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      january: "Unavailable",
      february: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "watercress",
    availability: {
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
    },
  },
  {
    name: "witloof",
    availability: {
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "yam",
    availability: {
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "rhubarb",
    availability: {
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
  {
    name: "persimmon",
    availability: {
      may: "Available",
      june: "Available",
      january: "Unavailable",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
      december: "Unavailable",
    },
  },
];
