export const produce = [
  {
    name: "blackcurrant",
    availability: {
      january: "Available",
      february: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "redcurrant",
    availability: {
      january: "Available",
      december: "Available",
      february: "Unavailable",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
  {
    name: "puha",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "salad greens",
    availability: {
      january: "Available",
      february: "Available",
      march: "Available",
      april: "Available",
      may: "Available",
      june: "Available",
      july: "Available",
      august: "Available",
      september: "Available",
      october: "Available",
      november: "Available",
      december: "Available",
    },
  },
  {
    name: "taewa",
    availability: {
      january: "Available",
      february: "Available",
      december: "Available",
      march: "Unavailable",
      april: "Unavailable",
      may: "Unavailable",
      june: "Unavailable",
      july: "Unavailable",
      august: "Unavailable",
      september: "Unavailable",
      october: "Unavailable",
      november: "Unavailable",
    },
  },
];
